## Nornir 3.0 Config File 

inventory:
    plugin: SimpleInventory
    options: 
        host_file: "/home/roger/nornir-course/inventory/hosts.yml"
        group_file: "/home/roger/nornir-course/inventory/groups.yml"
        defaults_file: "/home/roger/nornir-course/inventory/defaults.yml"

runner: 
    plugin: threaded
    options: 
        num_workers: 20
