## Nornir 3.0 Config File 

inventory:
    plugin: SimpleInventory
    options: 
        host_file: "~/network-programmability/SCRIPTS/Nornir/inventory/hosts.yml"
        group_file: "~/network-programmability/SCRIPTS/Nornir/inventory/groups.yml"
        defaults_file: "~/network-programmability/SCRIPTS/Nornir/inventory/defaults.yml"

runner: 
    plugin: threaded
    options: 
        num_workers: 20
