## Nornir Groups File 
---
CSR_Routers: 

  data: 
    ntp: 
      servers: 
        - 1.1.1.1

CSR: 

   data: 
     ntp:
       servers:
        - 2.2.2.2

UK: 

    data:
      ntp: 
        servers:
         - 3.3.3.3
